using LRSchoolV2.Domain.AnnualServices;

namespace LRSchoolV2.Application.AnnualServices.AnnualServiceVariations.DeleteAnnualServiceVariation;

public record DeleteAnnualServiceVariationRequest(AnnualServiceVariation AnnualServiceVariation);
