using LRSchoolV2.Domain.AnnualServices;

namespace LRSchoolV2.Application.AnnualServices.AnnualServiceVariationConsultantWorks.DeleteAnnualServiceVariationConsultantWork;

public record DeleteAnnualServiceVariationConsultantWorkRequest(AnnualServiceVariationConsultantWork AnnualServiceVariationConsultantWork);
