namespace LRSchoolV2.Application.AnnualServices.AnnualServiceVariationYearlyPrices.GetAnnualServiceVariationYearlyPricesPerAnnualServiceVariation;

public static class GetAnnualServiceVariationYearlyPricesPerAnnualServiceVariationRequestValidationErrors
{
    public const string AnnualServiceVariationNotFound = "La variation n'a pas été trouvé";
}