namespace LRSchoolV2.Application.AnnualServices.AnnualServiceVariationYearlyPrices.GetAnnualServiceVariationYearlyPricesPerAnnualServiceVariation;

public record GetAnnualServiceVariationYearlyPricesPerAnnualServiceVariationRequest(Guid AnnualServiceVariationId);