using LRSchoolV2.Application.AnnualServices.AnnualServiceVariationYearlyPrices.Persistence;
using MediatR;

// ReSharper disable UnusedType.Global - Implicit use

namespace LRSchoolV2.Application.AnnualServices.AnnualServiceVariationYearlyPrices.SaveAnnualServiceVariationYearlyPrice;

public class SaveAnnualServiceVariationYearlyPriceHandler(IAnnualServiceVariationYearlyPricesRepository inAnnualServiceVariationYearlyPricesRepository) : IRequestHandler<SaveAnnualServiceVariationYearlyPriceCommand>
{
    public Task Handle(SaveAnnualServiceVariationYearlyPriceCommand inRequest, CancellationToken inCancellationToken) => 
        inAnnualServiceVariationYearlyPricesRepository.SaveAnnualServiceVariationYearlyPriceAsync(inRequest.AnnualServiceVariationYearlyPrice);
}