

// ReSharper disable ClassNeverInstantiated.Global - Implicit use

using LRSchoolV2.Domain.AnnualServices;

namespace LRSchoolV2.Application.AnnualServices.AnnualServiceVariationYearlyPrices.SaveAnnualServiceVariationYearlyPrice;

public record SaveAnnualServiceVariationYearlyPriceRequest(AnnualServiceVariationYearlyPrice AnnualServiceVariationYearlyPrice);
