namespace LRSchoolV2.Application.ConsultantInvoices.ConsultantInvoiceItems.GetConsultantInvoiceItemsPerConsultantInvoice;

public record GetConsultantInvoiceItemsPerConsultantInvoiceRequest(Guid ConsultantInvoiceId);