namespace LRSchoolV2.Application.AnnualServices.AnnualServiceConsultantWorks.GetAnnualServiceConsultantWorksPerAnnualService;

public record GetAnnualServiceConsultantWorksPerAnnualServiceRequest(Guid AnnualServiceId);