using LRSchoolV2.Domain.AnnualServices;

namespace LRSchoolV2.Application.AnnualServices.AnnualServiceConsultantWorks.GetAnnualServiceConsultantWorksPerAnnualService;

public record GetAnnualServiceConsultantWorksPerAnnualServiceResponse(IEnumerable<AnnualServiceConsultantWork> AnnualServiceConsultantWorks);
