using LRSchoolV2.Domain.AnnualServices;
using MediatR;

// ReSharper disable ClassNeverInstantiated.Global - Implicit use

namespace LRSchoolV2.Application.AnnualServices.AnnualServiceVariationConsultantWorks.SaveAnnualServiceVariationConsultantWork;

public record SaveAnnualServiceVariationConsultantWorkCommand(AnnualServiceVariationConsultantWork AnnualServiceVariationConsultantWork) : IRequest;
