using LRSchoolV2.Domain.ConsultantInvoices;

namespace LRSchoolV2.Application.ConsultantInvoices.ConsultantInvoices.CancelConsultantInvoice;

public record CancelConsultantInvoiceRequest(ConsultantInvoice ConsultantInvoice);