namespace LRSchoolV2.Application.ConsultantQuotes.ConsultantQuoteItems.GetConsultantQuoteItemsPerConsultantQuote;

public record GetConsultantQuoteItemsPerConsultantQuoteRequest(Guid ConsultantQuoteId);