using LRSchoolV2.Domain.AnnualServices;

namespace LRSchoolV2.Application.AnnualServices.AnnualServiceConsultantWorks.DeleteAnnualServiceConsultantWork;

public record DeleteAnnualServiceConsultantWorkRequest(AnnualServiceConsultantWork AnnualServiceConsultantWork);
