using LRSchoolV2.Domain.Persons;

namespace LRSchoolV2.Application.Persons.PersonAnnualServiceVariations.DeletePersonAnnualServiceVariation;

public record DeletePersonAnnualServiceVariationRequest(PersonAnnualServiceVariation PersonAnnualServiceVariation);
