using LRSchoolV2.Domain.CustomerInvoices;

namespace LRSchoolV2.Application.CustomerInvoices.CustomerInvoices.CancelCustomerInvoice;

public record CancelCustomerInvoiceRequest(CustomerInvoice CustomerInvoice);