namespace LRSchoolV2.Application.AnnualServices.AnnualServiceVariationConsultantWorks.GetAnnualServiceVariationConsultantWorksPerAnnualServiceVariation;

public record GetAnnualServiceVariationConsultantWorksPerAnnualServiceVariationRequest(Guid AnnualServiceVariationId);