using MediatR;

// ReSharper disable ClassNeverInstantiated.Global - Implicit use

namespace LRSchoolV2.Application.AnnualServices.AnnualServiceVariationConsultantWorks.GetAnnualServiceVariationConsultantWorksPerAnnualServiceVariation;

public record GetAnnualServiceVariationConsultantWorksPerAnnualServiceVariationQuery(Guid AnnualServiceVariationId) : IRequest<GetAnnualServiceVariationConsultantWorksPerAnnualServiceVariationResponse>;