using LRSchoolV2.Domain.AnnualServices;

namespace LRSchoolV2.Application.AnnualServices.AnnualServiceVariationConsultantWorks.GetAnnualServiceVariationConsultantWorksPerAnnualServiceVariation;

public record GetAnnualServiceVariationConsultantWorksPerAnnualServiceVariationResponse(IEnumerable<AnnualServiceVariationConsultantWork> AnnualServiceVariationConsultantWorks);
