using LRSchoolV2.Domain.CustomerPayments;

namespace LRSchoolV2.Application.CustomerPayments.CustomerPayments.DeleteCustomerPayment;

public record DeleteCustomerPaymentRequest(CustomerPayment CustomerPayment);
