using LRSchoolV2.Domain.AnnualServices;

namespace LRSchoolV2.Application.AnnualServices.AnnualServiceVariationYearlyPrices.DeleteAnnualServiceVariationYearlyPrice;

public record DeleteAnnualServiceVariationYearlyPriceRequest(AnnualServiceVariationYearlyPrice AnnualServiceVariationYearlyPrice);
