# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: ShikanokoNokonokoKo$h1tantan
        ports:
          - 1433:1433

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Wait for SQL Server to be ready
        run: |
          for i in {1..30}; do
            if sqlcmd -S localhost -U SA -P 'ShikanokoNokonokoKo$h1tantan' -Q "SELECT 1" &>/dev/null; then
              echo "SQL Server is up and running"
              break
            fi
            echo "Waiting for SQL Server..."
            sleep 5
          done

      - name: Test
        run: dotnet test --no-build --verbosity normal --logger "trx;LogFileName=test-results.trx"

      - name: Test Reporter
        uses: dorny/test-reporter@v1.9.1
        if: success() || failure()
        with:
          name: Test results
          path: "**/*.trx"
          reporter: dotnet-trx
          fail-on-error: true
            
