# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2019-latest
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: ShikanokoNokonokoKoshitantan
        ports:
          - 1433:1433
        options: >-
          --health-cmd "wget --quiet --tries=1 --spider http://localhost:1433 || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Wait for SQL Server to be ready
        run: |
          for i in {1..30}; do
            if sqlcmd -S localhost -U SA -P 'ShikanokoNokonokoKoshitantan' -Q "SELECT 1" &>/dev/null; then
              echo "SQL Server is up and running"
              break
            fi
            echo "Waiting for SQL Server..."
            sleep 5
          done

      - name: Test
        run: dotnet test --no-build --verbosity normal
